### ISSUE TITLE
Travis is broken?

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#950] opened 2017-10-11 07:04 UTC
The nightly builds aren't getting updated.  I have zero Travis-fu myself, I can't even figure out how to get to the build page.  Can someone find out what is wrong and fix it?

**Comment by mikeshulman** [comment] 2018-03-05 21:52
@JasonGross any time to look at this?

**Comment by iblech** [comment] 2018-03-05 22:23
I'm not Jason, but I believe that I know the cause of the build failure. I'm pushing a pull request which I believe Travis will try to build even if it's not yet merged. From the build logs we should then be able to see whether my attempted fix works.

Mike: You can examine the build log at https://travis-ci.org/HoTT/book, by clicking on one of the jobs.

**Comment by mikeshulman** [comment] 2018-03-05 23:07
Great, thanks!  I've merged #973, let's see what happens.

**Closed** 2018-03-05 23:07 UTC

**Comment by mikeshulman** [comment] 2018-03-05 23:24
Woot!  Seems to be fixed!  Thanks a bunch.

Just out of curiosity, do you have any idea what changed to cause this to break?  The original version *used* to work.

**Comment by iblech** [comment] 2018-03-15 14:28
I don't know right now, but the question piqued my curiosity and I'll investigate when I have time!

**Comment by JasonGross** [comment] 2018-03-15 14:36
There's some cutoff, and book versions older than that cutoff got deleted, if I recall correctly.  My guess is that the HoTT book used to be updated frequently enough that there were always at least two old versions of the book laying around, and the issue only arose when enough time passed between updates that there was only one old copy of the book, and it was too old? Alternatively, maybe whatever heuristics we were using to guess the dates of things stopped working?  Or maybe some date comparison got confused by year boundaries?
